using HackathonApi.Data;
using HackathonApi.Dtos;
using HackathonApi.Middleware;
using HackathonApi.Models;
using Microsoft.EntityFrameworkCore;

namespace HackathonApi.Services;

public class CaseService : ICaseService
{
    private const int MaxPageSize = 100;

    /// <summary>
    /// Reporter name stamped on the inspection reports this service raises, so
    /// they are distinguishable from public reports at a glance as well as by
    /// <see cref="Report.IsAutoGenerated"/>.
    /// </summary>
    private const string SystemReporterName = "System (case notification)";

    private readonly AppDbContext _db;

    public CaseService(AppDbContext db) => _db = db;

    public async Task<PagedResult<CaseDto>> GetCasesAsync(
        CaseQueryParameters query,
        CancellationToken cancellationToken = default)
    {
        var cases = _db.DengueCases
            .AsNoTracking()
            .Include(c => c.Division)
            .AsQueryable();

        if (query.DivisionId is not null)
        {
            cases = cases.Where(c => c.DivisionId == query.DivisionId);
        }

        var totalCount = await cases.CountAsync(cancellationToken);

        var page = query.Page < 1 ? 1 : query.Page;
        var pageSize = Math.Clamp(query.PageSize < 1 ? 10 : query.PageSize, 1, MaxPageSize);

        var results = await cases
            .OrderByDescending(c => c.ReportedDate)
            .ThenByDescending(c => c.Id)
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .Select(c => new CaseDto(
                c.Id,
                c.DivisionId,
                c.Division!.Name,
                c.ReportedDate,
                c.AgeBand,
                c.Severity,
                c.Hospitalised))
            .ToListAsync(cancellationToken);

        return new PagedResult<CaseDto>(results, totalCount, page, pageSize);
    }

    public async Task<CaseDto> CreateAsync(
        CreateCaseDto dto,
        CancellationToken cancellationToken = default)
    {
        var division = await _db.Divisions
            .FirstOrDefaultAsync(d => d.Id == dto.DivisionId, cancellationToken)
            ?? throw new NotFoundException("Division", dto.DivisionId);

        var reportedDate = ToUtc(dto.ReportedDate!.Value);

        var dengueCase = new DengueCase
        {
            DivisionId = division.Id,
            ReportedDate = reportedDate,
            AgeBand = dto.AgeBand!.Value,
            Severity = dto.Severity!.Value,
            Hospitalised = dto.Hospitalised
        };

        // Mirrors the MOH case-investigation process: a notified case triggers
        // an inspection of the premises around it, whether or not anyone has
        // reported a breeding site there. Raised in the same SaveChanges as the
        // case so the two can never come apart.
        var inspection = new Report
        {
            DivisionId = division.Id,
            SiteType = SiteType.PremisesInspection,
            Description =
                $"Case notified {reportedDate:yyyy-MM-dd} — conduct premises inspection in surrounding area",
            Landmark = string.Empty,
            ReporterName = SystemReporterName,
            ReporterPhone = string.Empty,
            Status = ReportStatus.Reported,
            ReportedAt = DateTime.UtcNow,
            IsAutoGenerated = true
        };

        _db.DengueCases.Add(dengueCase);
        _db.Reports.Add(inspection);

        await _db.SaveChangesAsync(cancellationToken);

        return new CaseDto(
            dengueCase.Id,
            division.Id,
            division.Name,
            dengueCase.ReportedDate,
            dengueCase.AgeBand,
            dengueCase.Severity,
            dengueCase.Hospitalised);
    }

    /// <summary>
    /// Npgsql rejects a non-UTC <see cref="DateTime"/> for a timestamptz column,
    /// and a client may well send a local or unspecified kind.
    /// </summary>
    private static DateTime ToUtc(DateTime value) => value.Kind switch
    {
        DateTimeKind.Utc => value,
        DateTimeKind.Local => value.ToUniversalTime(),
        _ => DateTime.SpecifyKind(value, DateTimeKind.Utc)
    };
}
