using HackathonApi.Data;
using HackathonApi.Dtos;
using HackathonApi.Middleware;
using HackathonApi.Models;
using Microsoft.EntityFrameworkCore;

namespace HackathonApi.Services;

public class ReportService : IReportService
{
    private const int MaxPageSize = 100;

    private readonly AppDbContext _db;
    private readonly IRiskService _risk;

    public ReportService(AppDbContext db, IRiskService risk)
    {
        _db = db;
        _risk = risk;
    }

    public async Task<PagedResult<ReportDto>> GetReportsAsync(
        ReportQueryParameters query,
        CancellationToken cancellationToken = default)
    {
        var reports = _db.Reports
            .AsNoTracking()
            .Include(r => r.Division)
            .AsQueryable();

        if (query.DivisionId is not null)
        {
            reports = reports.Where(r => r.DivisionId == query.DivisionId);
        }

        if (query.SiteType is not null)
        {
            reports = reports.Where(r => r.SiteType == query.SiteType);
        }

        if (query.Status is not null)
        {
            reports = reports.Where(r => r.Status == query.Status);
        }

        if (!string.IsNullOrWhiteSpace(query.Phone))
        {
            // Equality, not ILIKE: a resident looks up their own number, and a
            // prefix match would hand them somebody else's reports.
            var phone = query.Phone.Trim();
            reports = reports.Where(r => r.ReporterPhone == phone);
        }

        if (!string.IsNullOrWhiteSpace(query.Search))
        {
            // ILIKE keeps the match case-insensitive in Postgres itself.
            var pattern = $"%{Escape(query.Search.Trim())}%";
            reports = reports.Where(r =>
                EF.Functions.ILike(r.Description, pattern, "\\") ||
                EF.Functions.ILike(r.Landmark, pattern, "\\"));
        }

        // Risk score is computed, not stored, so the ordering cannot be pushed
        // into SQL: the filtered set is materialised, scored, then paged in
        // memory. Fine at this dataset's size; if reports ever grow past a few
        // thousand rows per query, persist the score and sort on it in the
        // database instead.
        var matched = await reports.ToListAsync(cancellationToken);

        var now = DateTime.UtcNow;

        var page = query.Page < 1 ? 1 : query.Page;
        var pageSize = Math.Clamp(query.PageSize < 1 ? 10 : query.PageSize, 1, MaxPageSize);

        var results = matched
            .Select(report => ToDto(report, now))
            .OrderByDescending(dto => dto.RiskScore)
            .ThenByDescending(dto => dto.ReportedAt)
            .ThenByDescending(dto => dto.Id)
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .ToList();

        return new PagedResult<ReportDto>(results, matched.Count, page, pageSize);
    }

    public async Task<ReportDto> GetByIdAsync(int id, CancellationToken cancellationToken = default)
    {
        var report = await _db.Reports
            .AsNoTracking()
            .Include(r => r.Division)
            .FirstOrDefaultAsync(r => r.Id == id, cancellationToken);

        if (report is null)
        {
            throw new NotFoundException("Report", id);
        }

        return ToDto(report, DateTime.UtcNow);
    }

    public async Task<ReportDto> CreateAsync(
        CreateReportDto dto,
        CancellationToken cancellationToken = default)
    {
        // Checked up front so an unknown division comes back as a 404 rather
        // than a foreign key violation from the database.
        var division = await _db.Divisions
            .FirstOrDefaultAsync(d => d.Id == dto.DivisionId, cancellationToken)
            ?? throw new NotFoundException("Division", dto.DivisionId);

        var report = new Report
        {
            DivisionId = division.Id,
            SiteType = dto.SiteType!.Value,
            Description = dto.Description.Trim(),
            Landmark = dto.Landmark?.Trim() ?? string.Empty,
            ReporterName = dto.ReporterName.Trim(),
            ReporterPhone = dto.ReporterPhone.Trim(),
            Status = ReportStatus.Reported,
            ReportedAt = DateTime.UtcNow,
            IsAutoGenerated = false
        };

        _db.Reports.Add(report);
        await _db.SaveChangesAsync(cancellationToken);

        report.Division = division;

        return ToDto(report, DateTime.UtcNow);
    }

    public async Task<ReportDto> UpdateStatusAsync(
        int id,
        UpdateReportStatusDto dto,
        CancellationToken cancellationToken = default)
    {
        var report = await _db.Reports
            .Include(r => r.Division)
            .FirstOrDefaultAsync(r => r.Id == id, cancellationToken)
            ?? throw new NotFoundException("Report", id);

        var status = dto.Status!.Value;

        // Stamped on the first move to Inspected only, so a correction or a
        // second visit does not overwrite the original inspection date.
        if (status == ReportStatus.Inspected && report.InspectedAt is null)
        {
            report.InspectedAt = DateTime.UtcNow;
        }

        report.Status = status;

        if (dto.InspectorNote is not null)
        {
            var note = dto.InspectorNote.Trim();
            report.InspectorNote = note.Length == 0 ? null : note;
        }

        await _db.SaveChangesAsync(cancellationToken);

        return ToDto(report, DateTime.UtcNow);
    }

    private ReportDto ToDto(Report report, DateTime asOfUtc) => new(
        report.Id,
        report.SiteType,
        SiteTypeLabels.For(report.SiteType),
        report.DivisionId,
        report.Division?.Name ?? string.Empty,
        report.Description,
        report.Landmark,
        report.ReporterName,
        report.Status,
        report.ReportedAt,
        report.InspectedAt,
        report.InspectorNote,
        Math.Round(_risk.ScoreReport(report, asOfUtc), 2),
        (int)Math.Floor(_risk.GetDaysOpen(report, asOfUtc)));

    /// <summary>Neutralises LIKE wildcards so a user's % or _ matches literally.</summary>
    private static string Escape(string value) => value
        .Replace("\\", "\\\\")
        .Replace("%", "\\%")
        .Replace("_", "\\_");
}
