using HackathonApi.Models;
using Microsoft.EntityFrameworkCore;

namespace HackathonApi.Data;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public DbSet<Division> Divisions => Set<Division>();

    public DbSet<Report> Reports => Set<Report>();

    public DbSet<DengueCase> DengueCases => Set<DengueCase>();

    public DbSet<Officer> Officers => Set<Officer>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<Division>(entity =>
        {
            entity.HasKey(d => d.Id);

            entity.Property(d => d.Id).ValueGeneratedOnAdd();

            entity.Property(d => d.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(d => d.MohArea)
                .HasMaxLength(100);

            entity.Property(d => d.District)
                .HasMaxLength(50);

            entity.HasIndex(d => d.Name);
            entity.HasIndex(d => d.District);
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(r => r.Id);

            entity.Property(r => r.Id).ValueGeneratedOnAdd();

            // Stored as text ("RoofGutter", "NoticeIssued") so the rows stay
            // readable and reordering the enum members cannot silently remap
            // existing data.
            entity.Property(r => r.SiteType)
                .HasConversion<string>()
                .HasMaxLength(32)
                .IsRequired();

            entity.Property(r => r.Status)
                .HasConversion<string>()
                .HasMaxLength(32)
                .IsRequired();

            entity.Property(r => r.Description)
                .HasMaxLength(500);

            entity.Property(r => r.Landmark)
                .HasMaxLength(200);

            entity.Property(r => r.ReporterName)
                .HasMaxLength(100);

            entity.Property(r => r.ReporterPhone)
                .HasMaxLength(15);

            entity.Property(r => r.InspectorNote)
                .HasMaxLength(500);

            entity.Property(r => r.ReportedAt).IsRequired();

            entity.Property(r => r.IsAutoGenerated).IsRequired();

            // Restrict, not Cascade: a division with reports against it must be
            // reassigned before it can be removed, never silently taking its
            // history with it.
            entity.HasOne(r => r.Division)
                .WithMany()
                .HasForeignKey(r => r.DivisionId)
                .OnDelete(DeleteBehavior.Restrict);

            entity.HasIndex(r => r.ReportedAt);
            entity.HasIndex(r => r.Status);
            entity.HasIndex(r => r.DivisionId);
        });

        modelBuilder.Entity<DengueCase>(entity =>
        {
            entity.HasKey(c => c.Id);

            entity.Property(c => c.Id).ValueGeneratedOnAdd();

            entity.Property(c => c.AgeBand)
                .HasConversion<string>()
                .HasMaxLength(32)
                .IsRequired();

            entity.Property(c => c.Severity)
                .HasConversion<string>()
                .HasMaxLength(32)
                .IsRequired();

            entity.Property(c => c.ReportedDate).IsRequired();

            entity.Property(c => c.Hospitalised).IsRequired();

            entity.HasOne(c => c.Division)
                .WithMany()
                .HasForeignKey(c => c.DivisionId)
                .OnDelete(DeleteBehavior.Restrict);

            entity.HasIndex(c => c.ReportedDate);
            entity.HasIndex(c => c.DivisionId);
        });

        modelBuilder.Entity<Officer>(entity =>
        {
            entity.HasKey(o => o.Id);

            entity.Property(o => o.Id).ValueGeneratedOnAdd();

            entity.Property(o => o.FullName)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(o => o.Email)
                .IsRequired()
                .HasMaxLength(150);

            entity.Property(o => o.PasswordHash)
                .IsRequired();

            entity.Property(o => o.MohArea)
                .HasMaxLength(100);

            entity.Property(o => o.Role)
                .HasConversion<string>()
                .HasMaxLength(32)
                .IsRequired();

            entity.Property(o => o.IsActive)
                .IsRequired()
                .HasDefaultValue(true);

            entity.Property(o => o.CreatedAt).IsRequired();

            // Email is the sign-in identifier, so it has to be unique across
            // deactivated accounts too — otherwise deactivating someone would
            // free their address for reuse and blur the audit trail.
            entity.HasIndex(o => o.Email).IsUnique();

            // Self-referencing: who created this account. Restrict for the same
            // reason as everywhere else — an account that admitted others
            // cannot be removed out from under them.
            entity.HasOne(o => o.CreatedBy)
                .WithMany()
                .HasForeignKey(o => o.CreatedById)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // Picks up any IEntityTypeConfiguration<T> declared in this assembly.
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);
    }
}
