using System.ComponentModel.DataAnnotations;

namespace HackathonApi.Models;

/// <summary>A public report of a suspected mosquito breeding site.</summary>
public class Report
{
    public int Id { get; set; }

    public SiteType SiteType { get; set; }

    public int DivisionId { get; set; }

    public Division? Division { get; set; }

    [MaxLength(500)]
    public string Description { get; set; } = string.Empty;

    /// <summary>Free-text locator, since reports rarely carry a street address.</summary>
    [MaxLength(200)]
    public string Landmark { get; set; } = string.Empty;

    [MaxLength(100)]
    public string ReporterName { get; set; } = string.Empty;

    [MaxLength(15)]
    public string ReporterPhone { get; set; } = string.Empty;

    public ReportStatus Status { get; set; } = ReportStatus.Reported;

    /// <summary>
    /// True when the row was raised by the system rather than by a member of
    /// the public — currently only the premises-inspection task opened whenever
    /// a dengue case is notified. These are work items, not observed breeding
    /// sites, so they are excluded from vector risk scoring.
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>Always stored as UTC.</summary>
    public DateTime ReportedAt { get; set; }

    /// <summary>Null until an inspector visits the site. Always stored as UTC.</summary>
    public DateTime? InspectedAt { get; set; }

    /// <summary>Set by the inspector at the same time as <see cref="InspectedAt"/>.</summary>
    [MaxLength(500)]
    public string? InspectorNote { get; set; }
}
